import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Typography from "@/components/atoms/Typography";
import { PiChats } from "react-icons/pi";
import ButtonIcon from "@/components/atoms/ButtonIcon";
import SidebarNav from "@/components/organisms/SidebarNav";
import Avatar from "@/components/atoms/Avatar";
import { PiSignOut } from "react-icons/pi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="bg-white w-[80px] flex flex-col items-center gap-5 py-8">
            <Typography variant="header" size="lg">
              S.
            </Typography>
            <ButtonIcon className="bg-yellow-300 text-neutral-700">
              <PiChats size={20} />
            </ButtonIcon>
            <SidebarNav />
            <div>
              <Avatar size={40} src="/profile.jpeg" />
              <ButtonIcon className="bg-neutral-100 text-neutral-700 pt-3 -mt-3">
                <PiSignOut size={20} />
              </ButtonIcon>
            </div>
          </div>
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
